### ISSUE TITLE
api q's

### ISSUE THREAD

**Issue by liamstask** [pkg/term#11]
I was curious whether the api for pkg `term` is intended to support more of the port settings (parity, stop bits, etc) - I don't currently see how to manipulate these currently, since the underlying `syscall.Termios` is not exported.

Relatedly, there appears to be no getter for speed/baud rate on a port, while there is a setter. Is this intentional, or is there an alternative? Thanks.

**Comment by davecheney** [comment]
The API existed to support the bits I needed to talk to an Arduino, If you
have new options or facilities you'd like, please feel free to raise
specific issues, or send PRs

Thanks

Dave

**Comment by liamstask** [comment]
ok, will do - thx!
