### ISSUE TITLE
golang.syscall to golang.org/x/sys

### ISSUE THREAD

**Issue by Konstantin8105** [pkg/term#38]
Hello,

In according to https://golang.org/pkg/syscall:

> Deprecated: this package is locked down. Callers should use the 
> corresponding package in the golang.org/x/sys repository instead.

In my point of view, we have to update.
Please clarify your point of view.

**Comment by davecheney** [comment]
Is there something missing from the syscall package that this package needs?

**Comment by Konstantin8105** [comment]
At the preliminary view, all is same, but with small separation by OS:
https://godoc.org/golang.org/x/sys

Also struct of `Termios` changed from:
```go
type Termios struct {
        Iflag     uint32
        Oflag     uint32
        Cflag     uint32
        Lflag     uint32
        Line      uint8
        Cc        [32]uint8
        Pad_cgo_0 [3]byte
        Ispeed    uint32
        Ospeed    uint32
}
```
to:
```go
type Termios struct {
    Iflag  uint32
    Oflag  uint32
    Cflag  uint32
    Lflag  uint32
    Line   uint8
    Cc     [19]uint8
    Ispeed uint32
    Ospeed uint32
}
```

**Comment by davecheney** [comment]
In which os? Was this change backported to the syscall package?

**Comment by Konstantin8105** [comment]
I only `unix` package. Us I understood, if fields of struct Termios are changed , so structs `syscall.Termios` and `unix.Termios` are not comparable. So no backport.

**Comment by davecheney** [comment]
I've switched to x/sys now.
