### ISSUE TITLE
Consider releasing a semantic version of term so it can be used with go mod

### ISSUE THREAD

**Issue by zacsketches** [pkg/term#47]
Good morning.  I've found this package to be quite robust for managing serial communications with some embedded systems work we are doing and would like to rely on it as a dependency.

We are using Go Modules and would appreciate it if you could release a tag with V0.1.0 or whatever version you feel is appropriate for now.

**Comment by pgollangi** [comment]
This can now be closed I believe since `v1.0.0` was released few days ago.
https://github.com/pkg/term/releases
