### ISSUE TITLE
pty not compatible with windows

### ISSUE THREAD

**Issue by Abbaskt** [pkg/term#50]
# github.com/pkg/term/termios
../go/src/github.com/pkg/term/termios/pty.go:20:14: undefined: open_pty_master
../go/src/github.com/pkg/term/termios/pty.go:25:16: undefined: Ptsname
../go/src/github.com/pkg/term/termios/pty.go:30:8: undefined: grantpt
../go/src/github.com/pkg/term/termios/pty.go:35:8: undefined: unlockpt

**Comment by davecheney** [comment]
Yes, that is correct. This package is not compatible with windows.

**Comment by davecheney** [comment]
Opps, my mistake. This package should work on windows. I don't use windows so I probably won't be able to resolve this myself.

**Comment by davecheney** [comment]
I'm sorry for the confusion. This project does not support windows, term/termios doesn't either as it is a unix specific package.
