### ISSUE TITLE
termios/pty_freebsd.go:10:15: undefined: unix

### ISSUE THREAD

**Issue by yurivict** [pkg/term#57]
The "o" project https://github.com/xyproto/o fails:
```
 github.com/pkg/term/termios
vendor/github.com/pkg/term/termios/pty_freebsd.go:10:15: undefined: unix
vendor/github.com/pkg/term/termios/pty_freebsd.go:19:22: undefined: unix
vendor/github.com/pkg/term/termios/pty_freebsd.go:24:19: undefined: unix
vendor/github.com/pkg/term/termios/pty_freebsd.go:33:19: undefined: unix
*** Error code 2
```

This is a regression between c3ffed290a03 and v1.1.0 (it was building fine in c3ffed290a03).

FreeBSD 12.2

**Comment by TByte007** [comment]
This is still a problem 

> # github.com/pkg/term/termios
> /home/tbyte/go/pkg/mod/github.com/pkg/term@v1.1.0/termios/pty_freebsd.go:10:15: undefined: unix
> /home/tbyte/go/pkg/mod/github.com/pkg/term@v1.1.0/termios/pty_freebsd.go:19:22: undefined: unix
> /home/tbyte/go/pkg/mod/github.com/pkg/term@v1.1.0/termios/pty_freebsd.go:24:19: undefined: unix
> /home/tbyte/go/pkg/mod/github.com/pkg/term@v1.1.0/termios/pty_freebsd.go:33:19: undefined: unix
> 

go version go1.20.12 freebsd/amd64 FreeBSD 14.0-RELEASE-p3
