### ISSUE TITLE
New release fixing FreeBSD build

### ISSUE THREAD

**Issue by zaynetro** [pkg/term#65]
Do mind publishing a new release soonish with FreeBSD build fixes? https://github.com/pkg/term/pull/61

**Comment by davecheney** [comment]
Does https://github.com/pkg/term/releases/tag/v1.2.0-beta.2 work for you? I can make that the 1.2.0 final release

**Comment by zaynetro** [comment]
Let's see if go-prompt's author will be OK with the beta release: https://github.com/c-bata/go-prompt/pull/224

I will keep you updated.

**Comment by zaynetro** [comment]
OK seems like using beta version is fine. Sorry for the false alarm!
